[platformio]
src_dir = PheonixMotoDisplay
default_envs = waveshare-knob-s3

[env:waveshare-knob-s3]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/54.03.20/platform-espressif32.zip
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 460800
board_build.flash_mode = qio
board_build.flash_size = 16MB
board_build.partitions = default_16MB.csv
board_build.psram_type = opi
board_build.memory_type = qio_opi
board_build.arduino.memory_type = qio_opi
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
build_flags =
    -DPHEONIX_WAVESHARE_KNOB
    -DBOARD_HAS_PSRAM
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1
lib_deps =
    lovyan03/LovyanGFX

[env:e32r28t]
platform = espressif32
board = esp32dev
framework = arduino
lib_ldf_mode = off
monitor_speed = 115200
upload_speed = 115200
board_build.flash_mode = dio
lib_deps =
    lovyan03/LovyanGFX
    ESP32 BLE Arduino
