[platformio]
src_dir = PheonixMotoDisplay

[env:e32r28t]
platform = espressif32
board = esp32dev
framework = arduino
lib_ldf_mode = off
monitor_speed = 115200
upload_speed = 115200
board_build.flash_mode = dio
lib_deps =
    lovyan03/LovyanGFX
    ESP32 BLE Arduino
